name: Build

on:
  - push

jobs:
  iOS:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: xcodebuild build -scheme MyAnimeList\ \(iOS\)
  tvOS:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: xcodebuild build -scheme MyAnimeList\ \(tvOS\)
